server:
  port: 9000
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/react
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
flyway:
  locations:  classpath:db/migration
logging:
  level:
    org:
      hibernate:  INFO
      springframework: INFO
