apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
data:
  username: cG9zdGdyZXM= #replace with base64 of username desired
  password: cGFzc3dvcmQ= #replace with base64 of password desired
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: disk
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "disk-1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres
        ports:
        - name: postgres-port
          containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        - name:  POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: database
              key: username
        - name:  POSTGRES_DB
          value:  react
        - name: PGDATA
          value:  "/var/lib/postgresql/data"
        volumeMounts:
        - name: postgres-storage
          mountPath: "/var/lib/postgresql/"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName:  claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
    targetPort: postgres-port
    protocol: TCP
  selector:
    app:  postgresdb
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crud-apis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crud-apis-backend
    spec:
      containers:
      - name: crud-apis-backend
        image: aardelean/appdirect-react-apis:1.1
        ports:
        - name: backend-port
          containerPort: 9000
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        - name: DATABASE_HOST
          value:  postgres-service
        - name: DATABASE_PORT
          value:  "5432"
        - name: DATABASE_NAME
          value:  react
---
apiVersion: v1
kind: Service
metadata:
  name: crud-apis-service
spec:
  ports:
  - port: 80
    targetPort: backend-port
    protocol: TCP
  selector:
    app:  crud-apis-backend
  type: LoadBalancer
