apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres
        ports:
        - name: postgres-port
          containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name:  POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name:  POSTGRES_DB
          value:  react
        - name: PGDATA
          value:  "/var/lib/postgresql/data"
        volumeMounts:
        - name: postgres-storage
          mountPath: "/var/lib/postgresql/data"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName:  claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
    targetPort: postgres-port
    protocol: TCP
  selector:
    app:  postgresdb
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crud-apis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crud-apis-backend
    spec:
      containers:
      - name: crud-apis-backend
        image: aardelean/appdirect-react-apis:1.1
        ports:
        - name: backend-port
          containerPort: 9000
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: DATABASE_HOST
          value:  postgres-service
        - name: DATABASE_PORT
          value:  "5432"
        - name: DATABASE_NAME
          value:  react
---
apiVersion: v1
kind: Service
metadata:
  name: crud-apis-service
spec:
  ports:
  - port: 80
    targetPort: backend-port
    protocol: TCP
  selector:
    app:  crud-apis-backend
  type: LoadBalancer
