ALTER TABLE PERSONS ADD PRIMARY KEY (id);
ALTER TABLE PERSONS ADD CONSTRAINT unique_person_id UNIQUE (id);
ALTER TABLE COMMENTS ADD PRIMARY KEY (id);
ALTER TABLE COMMENTS ADD CONSTRAINT unique_comment_id UNIQUE (id);
CREATE TABLE TWEETS (
	id BIGINT PRIMARY KEY UNIQUE,
	title varchar(255) not null,
	owner_id BIGINT REFERENCES PERSONS (id)
);
ALTER TABLE COMMENTS DROP COLUMN twitter_identifier;
ALTER TABLE COMMENTS ADD COLUMN tweet_id BIGINT REFERENCES TWEETS (id);
ALTER TABLE COMMENTS ADD COLUMN owner_id BIGINT REFERENCES PERSONS (id);
